### PR TITLE
MQTT feature request (with code)

### PR DESCRIPTION
**Pull request by kjkoster**
By allowing forward slashes as I/O names the I/O fields can be organised in a hierarchy on MQTT. This already works nicely for data coming from revpipyload into MQTT. It just did not work for setting I/O values using `.../set/...` topics. My proposed code resolves that and makes it work both ways.

I also made some changes to how errors are logged. They now always have the I/O name, which should aid troubleshooting.

Please consider this patch.

### CODE REVIEW

**Comment by kjkoster** [comment]
Hi @naruxde have you had time to look at this, please?

**Comment by naruxde** [comment]
Hi @kjkoster!

Fist of all, it makes sense to fix the ability to set IO values with a `/`in the name...

Maybe wie could enhance the topic check in line 240 with `if len(lst_topic) < 2 or lst_topic[0] not in ("get", "set", "reset"):`.

What I don't like at all is the possibility of using characters like "/" in the IO names. In my opinion, this is a design mistake in piCtory... It should allow only characters which are valid for names in all programming languages.
So if you use characters like "/" for IO names in piCtory, RevPiModIO can handle it and the programmer has to get the IO by using the name index of the io object. So you have to use `.io["test/I_2"]` instead of `.io.test/I_2`, which is of course a syntax error...

If you are using just the MQTT function, okay, piCtory allows us to use names with special characters, so wie could merge it.. But maybe we should think about other configurations for the future.

What do you think?

**Comment by kjkoster** [comment]
Thank you for your consideration.

We have 5 I/O modules, each with a bunch of sensors and actuators. The ability to group these into logical groups is a godsend, because it is really hard to find everything. In a flat list, it is easy to look at a motor speed and a flow and think these are related when they are not. In a hierarchy, this problem is less.

I agree that this is probably an oversight in pictory, but to me it is a lucky one. I'd argue that people use hierarchical naming anyway. I see lots of `motor1_speed`, `motor1_power`, `motor2_speed`, `motor2_power` naming. So I think it would look good on pictory to support what people need (logical I/O organisation), rather than what the hardware needs (device/port mappings).

You point about programming readability is valid, but my code only ever used the `.io["name"]` format. Iterating over lists forces that syntax anyway. Again, since all our stuff has so much similarities, we have lots of for loops over the set of devices. I am sure others will argue the opposite.

Alternatively, you could map `.io["foo/bar"]` onto `.io.foo.bar` and still have both? That would even be ideal for languages that have a `WITH` keyword: `WITH io.foo { print(bar); }` and you could iterate like that and have readable code.

**Comment by kjkoster** [comment]
I like your suggestion about line 240, but you'd need an ending error condition anyway, in case of a programming error in the if-else tree.

**Comment by kjkoster** [comment]
@naruxde any progress on thoughts?

**Comment by kjkoster** [comment]
Awesome.

**Pull request merged**
